name = "FriendsPack"
author = "bernesto"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fbc5c88675d4a5548f9915d34bbb05ffa821dc47b8a0846f35db60313b82782"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
